version: '2'
services:
  rstudio:
    build: sparklyr
    image: sparklyrstudio
    links: 
      - postgres
    ports:
      - "8787:8787" #rstudio webUI
    volumes:
      - ./rspark-notes:/home/rstudio/rspark-notes
      - ./rspark-tests:/home/rstudio/rspark-tests
  postgres:
      build: ./postgres
      image: jh-postgres
      ports:
        - "5432:5432"
      volumes:
        - ./data/pg-data:/opt/pg-data
