- name: install docker ce on Ubuntu or Debian
  hosts: localhost
  become: yes
  become_method: sudo
  gather_facts: yes
 
  tasks:
  - debug: msg="play_hosts={{play_hosts}}"
  - debug: msg="ansible_distribution={{ansible_distribution}}"
    
  - name: Install Dependencies
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - python-pip
    become: true
 
#  - name: install python modules (for older versions of OS)
#    pip:
#      name: "{{item}}"
#      state: present
#    with_items:
#    - urllib3
#    - pyOpenSSL
#    - ndg-httpsclient
#    - pyasn1
      
  - name: Add docker key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: true
    when: "ansible_distribution == 'Ubuntu'"
     
  - name: Create Repo Path
    command: bash -c "echo \"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\" "
    register: docker_repo_line
 
  - debug: 
      msg: "{{ docker_repo_line.stdout }}"
 
  - name: Add Repo
    apt_repository:
      repo: "{{ docker_repo_line.stdout }}"
      state: present
    become: true
      
  - name: Install Docker CE
    apt:
      name: docker-ce
      state: present
      update_cache: yes
    become: true

  - name: Install Docker-Compose - Step 1
    command: sudo curl -L https://github.com/docker/compose/releases/download/$dockerComposeVersion/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

  - name: Install Docker-Compose - Step 2
    command: sudo chmod +x /usr/local/bin/docker-compose

