---
- hosts: localhost
  sudo: yes
  tasks:

  - name: install base packages
    apt: pkg={{item}} state=present update_cache=yes cache_valid_time=604800
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - git
      - cloud-init
      - docker-compose

      # clone rspark repo to machine
  - git:
      repo: git://github.com/jharner/rspark
      dest: /opt/rspark
      clone: yes

      # create docker group
  - group:
      name: docker
      state: present

      # install docker using cloudinit
  - name: docker cloudinit 1 of 2
    command: curl -fsSL get.docker.com -o get-docker.sh
  - name: docker cloudinit 2 of 2
    command: sh get-docker.sh

      # add default user 'ubuntu' to group 'docker'
  - name: add user to docker group
    command: usermod -aG docker ubuntu

      # restart docker to commit changes
  - name: restart docker
    command: service docker restart

#  - name: build and run containers
#    command: /home/ubuntu/rspark/start.sh build




#### NOTES
#
#
# expose 8787!
#
# scp -i ./ansible/ansibletest.pem -r ./rspark-notes/* ubuntu@{IP}:/home/ubuntu/rspark/rspark-notes/
#



...