---

 - name: Run with inline v2 compose
   hosts: webserver
   connection: ssh
   gather_facts: no
   tasks:
    - name: install base packages
      apt: pkg={{item}} state=present update_cache=yes cache_valid_time=604800
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
        - git
        - cloud-init
        - docker-compose

#    - docker_service:
#        project_source: /home/ubuntu/rspark/

    - docker_service:
        project_name: rspark
        state: present
        definition:
          version: '2'
          services:
            postgres:
#              build: /home/ubuntu/rspark/postgres
              image: jh-postgres
              ports:
                - "5432:5432"
            hive:
#              build: /home/ubuntu/rspark/hive
              image: jh-hive
              ports:
                - "10000:10000"
              depends_on:
                - hadoop
            hadoop:
#              build: /home/ubuntu/rspark/hadoop
              image: jh-hadoop
              volumes:
                - /home/ubuntu/rspark/data/hadoop:/opt/hadoop
              ports:
                - "9000:9000" # Hadoop
                - "50070:50070" # HadoopUI Access
            rstudio:
#              build: /home/ubuntu/rspark/rstudio
              image: jh-rstudio
              ports:
                - "8787:8787" # RstudioUI
              links:
                - hadoop
                - postgres
              volumes:
                - /home/ubuntu/rspark/rspark-notes:/home/rstudio/rspark-notes
                - /home/ubuntu/rspark/rspark-tests:/home/rstudio/rspark-tests
              depends_on: 
                - hadoop
                - hive



...